### ISSUE TITLE
Module dependency issues

### ISSUE THREAD

**Issue by saraswat** [jihunchoi/unsupervised-treelstm#6]
Greetings -- It appears that the code depends on some modules that have recently had some API changes, hence the code does not work with current versions.

Can you provide the versions of `torch`, `tensorboard`, `torchtext` that the code works with?

I am trying to run `sst.train`.

The first problem is:

```
AttributeError: module 'tensor board' has no attribute 'FileWriter'
```
A workaround is: 

`pip install tensorboard==1.0.0a6` 

Now the next problem is:
```
 File "...unsupervised-treelstm/model/treelstm.py", line 189, in forward
    state = state.chunk(num_chunks=2, dim=2)
TypeError: chunk() missing 1 required positional arguments: "chunks"
```
Thanks.

**Comment by jihunchoi** [comment]
Sorry for the late reply.
Many APIs are changed in v0.3 and v0.4, however the code is implemented under v0.2.
However I think the errors can be easily fixed just by adding or modifying a few words and lines.

1) I used the `dmlc/tensorboard` library for plotting, however it seems that it is no longer maintained actively. I suggest you use the similar active library, `lanpa/tensorboard-pytorch` instead if you like the tensorboard interface. Or you can just use 1.0.0a6 version of the `dmlc/tensorboard` library just as the workaround you've found.
2) Maybe in pytorch v0.3, the `num_chunks` named argument changed its name to `chunks`. You can just rename the argument: `/num_chunks/chunks/g`. It would work in v0.4 too, however if you're using v0.4, don't forget to modify parts containing `volatile` variables and removing the use of variables (since they're now subsumed in tensors).

I think [the article](https://pytorch.org/2018/04/22/0_4_0-migration-guide.html) from the official pytorch team would help!
